### ISSUE TITLE
Follow namespace standard on plugin examples

### ISSUE THREAD

**Issue by kindermoumoute** [intelsdi-x/snap-plugin-lib-py#14]
In order promote [best practice](https://github.com/intelsdi-x/snap/blob/master/docs/PLUGIN_AUTHORING.md#plugin-metric-namespace) across every plugins, we should the following namespace standard on plugin examples: `/<organization>/<plugin_name>/...`.

[In the random collector](https://github.com/intelsdi-x/snap-plugin-lib-py/blob/master/examples/collector/rand.py#L86-L88), the used standard is `/random/...`.

I suggest we use `/intel/random/...` instead (or `/org/random/...`).

See also: https://github.com/intelsdi-x/snap-plugin-lib-cpp/issues/24

**Comment by mkleina** [comment]
You are totally right, I think namespace building convention should be consistent, so external plugin developers can follow it.
